kind = "mobile"
previewPath = "/mobile/"
title = "Cinematic Villa Mobile"
version = "1.0.0"
id = "artifacts/cinematic-villa-mobile"
router = "expo-domain"

[[integratedSkills]]
name = "expo"
version = "1.0.0"

[[services]]
ensurePreviewReachable = "/status"
name = "expo"
paths = [ "/mobile/" ]
localPort = 24790

[services.development]
run = "pnpm --filter @workspace/cinematic-villa-mobile run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/cinematic-villa-mobile", "run", "build" ]
run = [ "pnpm", "--filter", "@workspace/cinematic-villa-mobile", "run", "serve" ]

[services.env]
PORT = "24790"
BASE_PATH = "/mobile/"
